### ISSUE TITLE
Change scene

### ISSUE THREAD

**Issue by lfabiani** [yshrkt/VuforiaSampleSwift#1]
Hi Yoshihiro,

thank you for this project, it is very well written and very useful for me.

I have a question: is it possible to change the scene dynamically at runtime? Not the content of the scene, but the entire scene with another, for example in relation to the framed trackerable image.

Best regards,

Luca.

**Comment by yshrkt** [comment]
Hi Luca,

Thank you for your question.
You will be able to change scene according to the tracking targets.
I updated sample code now. Please try it!

**Comment by lfabiani** [comment]
Hi Yoshihiro,

thank you so much!! It works very well, it does exactly what I was wondering.

Best regards,

Luca.
