### ISSUE TITLE
xCode 8 issues: ViewController' does not conform to protocol 'VuforiaEAGLViewSceneSource'

### ISSUE THREAD

**Issue by markleeyw** [yshrkt/VuforiaSampleSwift#10]
After upgrade to xCode 8 ... swift 3 (recommend) ....  not working when I download this default project

 'ViewController' does not conform to protocol 'VuforiaEAGLViewSceneSource'

Any Advice?

**Comment by yshrkt** [comment]
@markleeyw 
I updated this project to support Xcode8 and Swift3. Please try new version.
Maybe failed to convert syntax of these protocol methods...
