### ISSUE TITLE
iPhone6+ iOS 10.0.0.2 , box(3D object) not showing at all

### ISSUE THREAD

**Issue by diamondian** [yshrkt/VuforiaSampleSwift#19]
Hi yshrkt, first of all , thanks for this awesome project, as it lightens a path for swift user like me(who know nothing about c++,and objc).

I managed getting this project up on phone with camera working fine, but when aiming to the target images, nothing shows up in the camera field,but i can see the outputs "stones/chips scene" switching between each other. Therefore i guess the vufuria is working fine ,as the images can be detected , just somehow something went wrong with the rendering. 

I haven't enough knowlege to figure out how opengl/metal level things work, if anyone could give me hint or a direction to solve this problem would be very appreciated!

//-------------------- logging outputs attached ---------------------------
2016-12-24 22:50:23.694867 VuforiaSampleSwift[1249:397838] [DYMTLInitPlatform] platform initialization successful
2016-12-24 22:50:23.779077 VuforiaSampleSwift[1249:397739] Metal GPU Frame Capture Enabled
2016-12-24 22:50:23.779288 VuforiaSampleSwift[1249:397739] Metal API Validation Enabled
default scene
2016-12-24 22:50:23.960802 VuforiaSampleSwift[1249:397868] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-12-24 22:50:23.965360 VuforiaSampleSwift[1249:397868] [MC] Reading from public effective user settings.
2016-12-24 22:50:23.972589 VuforiaSampleSwift[1249:397868] INFO/AR(1249) 2016-12-25 22:50:23: Vuforia selected rendering API OpenGL ES 2.x
2016-12-24 22:50:23.972636 VuforiaSampleSwift[1249:397868] INFO/AR(1249) 2016-12-25 22:50:23: Vuforia SDK version 6.2.6
2016-12-24 22:50:24.096698 VuforiaSampleSwift[1249:397868] Rendering mode set to: OpenGL ES 2.0
2016-12-24 22:50:24.122686 VuforiaSampleSwift[1249:397868] Rendering mode set to: OpenGL ES 2.0
2016-12-24 22:50:24.123015 VuforiaSampleSwift[1249:397739] DEBUG/AR(1249) UIView has CAEAGLLayer layer class
2016-12-24 22:50:24.123042 VuforiaSampleSwift[1249:397739] DEBUG/AR(1249) UIView responds to selector renderFrameVuforia
2016-12-24 22:50:24.150001 VuforiaSampleSwift[1249:397897] loadObjectTrackerDataSet (Tarmac.xml)
2016-12-24 22:50:24.151243 VuforiaSampleSwift[1249:397897] INFO/AR(1249) 2016-12-25 22:50:24: ObjectTracker: Successfully created dataset
2016-12-24 22:50:24.151496 VuforiaSampleSwift[1249:397897] INFO: successfully loaded data set
2016-12-24 22:50:24.196934 VuforiaSampleSwift[1249:397897] Successfully activated data set.
did finish preparing

2016-12-24 22:50:24.215602 VuforiaSampleSwift[1249:397897] VideoBackgroundConfig: size: 750,1334
2016-12-24 22:50:24.216327 VuforiaSampleSwift[1249:397897] VideoMode:w=1920 h=1080
2016-12-24 22:50:24.216447 VuforiaSampleSwift[1249:397897] width=750.000 height=1334.000
2016-12-24 22:50:24.216464 VuforiaSampleSwift[1249:397897] ViewPort: X,Y: 0.0,0.0 Size X,Y:750.0,1334.0
2016-12-24 22:50:24.372553 VuforiaSampleSwift[1249:397829] Deleting old image data @ 0x0
2016-12-24 22:50:24.372603 VuforiaSampleSwift[1249:397829] Created new image data buffer @ 0x109e54000 w/ 3110400 bytes
chips scene
//---------------------------------------------------------- end -------------------------

**Comment by chriskilpin** [comment]
I'm having a similar issue. Object recognition seems to be working but SceneKit rendering is broken. 
I am using the latest version of the SDK vuforia-sdk-ios-6-2-6 which is different from the version used in this project so maybe that is the cause of the problem. I see based on the output above @diamondian is using the same version of the SDK as me.

**Comment by agates4** [comment]
same issue here

**Comment by zporenta** [comment]
I've got the same issue.
Did anybody got it to work?

**Comment by mtrezza** [comment]
same issue here

**Comment by interactivetech** [comment]
Hey all!

I have the same issue. After struggling for hours on it, I noticed that the object sort of begins to appear when you shrink/downsample the image target. That made me realize its an issue with the camera position in scene kit to the actual scenekit scene.

Setting the planeNode and boxNode's position to an offset (I just chose <0,0,-10>) you can see the virtual objects.

In the func createStonesScene() function, 

Add the following code:
   planeNode.position = SCNVector3Make(0, 0, -10)
   boxNode.position = SCNVector3Make(0, 0, -10);

And you should see the virtual objects.

**Comment by mtrezza** [comment]
@interactivetech So did you solve the issue completely? Does the app work for you?

**Comment by interactivetech** [comment]
@mtrezza I am experimenting as I go. It seems that the code scales the scene kit scene based on some value, and the big issue seems to be with the projection matrix initialization. I feel fixing the projection matrix and changing the _objectScale property would solve the issue and render correctly.

Changing this code to in VuforiaManager.mm :
    _projectionMatrix = Vuforia::Tool::getProjectionGL(cameraCalibration, 0.05f, 5000.0f);


 changing _objectScale in VuforiaEAGLView.mm to :
        _objectScale = 0.1f;

and changing the size of the SCNPlane in to : 

planeNode.geometry = SCNPlane(width: 247.0*view.objectScale, height: 173.0*view.objectScale)

Fixed it for me. 

I also commented out this line of code in  VuforiaEAGLView.mm

VuforiaEAGLViewUtils::translatePoseMatrix(0.0f, 0.0f, _objectScale, &modelViewMatrix.data[0]);


I can push my code to github if that would help.

Here is a screenshot of it working on my phone 6s:

![img_2150](https://cloud.githubusercontent.com/assets/5833510/23090175/518abada-f565-11e6-9f4b-ed9728564034.PNG)

**Comment by mtrezza** [comment]
@interactivetech I changed the code like you described it but the cube does not stay on the marker. Could you push your code on github please? The result for me is: http://bit.ly/2ltuJaZ

**Comment by interactivetech** [comment]
Hey, what iPhone are you using? I am using the 6S+

**Comment by mtrezza** [comment]
I am using an iPhone 7 Plus. Do you think that is the reason why it looks different?

**Comment by interactivetech** [comment]
I am reading whether the screen resolution affects the perspective viewing, but to make it easier, the object scale is too small. Make it higher like .2 or .3, and play with object scale until the size is good.

Another thing is does the box disappear when you get too close to the marker?

**Comment by mtrezza** [comment]
I can put the objectScale up to 25.0f and the cube never gets as big as in your photo. Maybe you have changed more in code than you described above?

**Comment by interactivetech** [comment]
Sorry, I mean make the _objectScale smaller, Make it between 0.05f and 0.9f, the _objectScale will get multiplied.

Here is the link to my code pushed to github, see if this will work better for you!

https://github.com/interactivetech/VuforiaScenekit

**Comment by mtrezza** [comment]
You're a genius, it works! On iPhone and iPad.

**Comment by mtrezza** [comment]
You're a genius, it works! On iPhone and iPad.

To cover the whole marker the size of the plane should be set to the size of the marker in the XML file divided by the object scale:
`planeNode.geometry = SCNPlane(width: 0.247/view.objectScale, height: 0.173/view.objectScale)`

**Comment by interactivetech** [comment]
Your code fix works really great! I want to learn why the _objectScale at 0.1 works really well with the size of the marker in the XML file. I would want to have this object scale property automatically calibrated by the image marker. I will read more into the theory of mapping marker coordinates to image coordinates to see what I can do!

**Comment by mtrezza** [comment]
The image marker is of an arbitrarily defined size, as specified in the XML file. If the marker size is defined as `m*n` then a plane of size `m*n` covers it completely at an object scale of 1.

So the unit is arbitrary.

In the current code sample the object scale is `0.1` so the box has to be `1/0.1` the size of the marker.
The marker is defined as `0.247 x 0.173` so cover the whole marker the plane size as to be `247 x 173` which is the same as `0.247/objectScale x 0.173/objectScale`.

**Comment by xudesheng** [comment]
I'm using an old iPhone 5 for testing and in my case a new line boxNode.position = SCNVector3Make(0, 0, -15) before scene.rootNode.addChildNode(boxNode) solves issue. I don't need to change from 247.0/173.0 to 0.247/0.173.

I don't understand why you add var rootNode = SCNNode() but indeed rootNode is never used.

anyway, your code gave me tip which solved my issue. thanks a lot.

**Comment by interactivetech** [comment]
hey @xudesheng , sorry, that was an unused SCNNode I was going to use. I pushed code removing that, thanks for bringing it up! Did you change the _projectionMatrix and the _objectScale like I brought up in one of the comments? Changing only  the position of the boxNode would not change the issue that when you get your phone close to the marker, the scenekit camera will cut off the rendering.

Vuforia handles different intrinsic parameters for different phones automatically, but the scenekit scene in this project does not compensate the different object scales for different devices. I hope to be able to fix this to be less of a hassle for us.

**Comment by xudesheng** [comment]
@interactivetech Thank you for your prompted response.

You are RIGHT!!! After I modified _projectionMatrix and _objectScale, it works exactly as your screenshot at this old iPhone 5 and it's what I need.

Thank you again!

**Comment by mtrezza** [comment]
@interactivetech So it works on iPhone5, iPhone 6S, iPhone 7 Plus and iPad Air 2 with the object scale 0.1. So the code seems to be universal for all devices.

**Comment by xudesheng** [comment]
@interactivetech After more study in code, I changed near plane to 1.0 and also changed objectScale to 1.0. Overall feeling is better when I move camera around.
BTW, original line 494 in VuforiaManager.mm should be removed. It will cause destroyDataSet fail later when you embed this ViewController in other app.

**Comment by NicoHinderling** [comment]
Just wanted to say thank you to @interactivetech and @mtrezza for sleuthing this :)

**Comment by leeprobert** [comment]
Thank you guys! Great work sorting this out. You should fork the original project too.

**Comment by NicoHinderling** [comment]
@leeprobert Feel free to check out my fork. I added some other models
