### ISSUE TITLE
How to add my own image targets? 

### ISSUE THREAD

**Issue by MashaelSaeedi** [yshrkt/VuforiaSampleSwift#21]
Hi , Thanks for your amazing Code!! 
I was wondering how can i add my own image targets? i tested new image targets and add it to my own database in vuforia .. i add my image target (.dat, .xml) to image targets folder. but it says there's an error in loading it. so i think it's more than just adding it to the project. 

Thanks in advance!!

**Comment by eisenbruch** [comment]
@iMishaDev what was your solution?
