### ISSUE TITLE
VuMark support

### ISSUE THREAD

**Issue by leeprobert** [yshrkt/VuforiaSampleSwift#24]
Does this project support VuMarks?

**Comment by yshrkt** [comment]
@leeprobert 
Yes, this project support VuMarks.
You can set VuMark's xml file instead of Image Target's xml file.

![screen shot 2017-04-25 at 20 34 43](https://cloud.githubusercontent.com/assets/990692/25383402/edeb2700-29f6-11e7-83eb-aec67c2210f6.png)
