### ISSUE TITLE
Touch area offset

### ISSUE THREAD

**Issue by DanijelHuis** [yshrkt/VuforiaSampleSwift#26]
Hi,

It seems there is offset on touch area(hit detection), I've attached image to better explain it, blue area is where hit test succeeds.

![img_0011](https://cloud.githubusercontent.com/assets/5382135/26655076/826c12b2-4659-11e7-8abb-e149381baf17.jpg)

I am testing sample code on iphone 5 iOS 10.
Thanks for the sample!

**Comment by yshrkt** [comment]
@DanijelHuis Thanks for reporting issue. I fixed this issue.
