### ISSUE TITLE
Does "dataSet" destroy too early?

### ISSUE THREAD

**Issue by Meonardo** [yshrkt/VuforiaSampleSwift#28]
@yshrkt Thanks for the great solution to bring Vuforia to SceneKit!
When I pop the viewcontroller(own the scene) I got this error log: "**_ObjectTracker: ObjectTracker is shut down but 1 datasets have not been destroyed._**", so I found this method:

>  - (BOOL)deactivateDataSet:(Vuforia::DataSet *)theDataSet{
...
_dataSet = nil;(1)
...
> }

Does "_dataSet" destroy early to cause the 

> destroyDataSet(_dataSet)

 method return false? After I comment line (1), no error displayed, could you please check it if i was right.

**Comment by yshrkt** [comment]
@Meonardo Thanks, You're right. I fixed it.
