### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by Meonardo** [yshrkt/VuforiaSampleSwift#29]
The call stack is down below:
<img width="585" alt="crashed 2x" src="https://user-images.githubusercontent.com/13954438/29921629-ea01e8c0-8e84-11e7-966d-4a12dcb51f45.png">
 
I have a mapView which is also rendered by the opengl es, but they are not in the same scene. I also found when I scroll the collectionView (the eaglView's sibling view) the camera responses slowly. I m not sure this is your issue, please help me out. thanks!

**Comment by yshrkt** [comment]
Is your problem likes [this](https://stackoverflow.com/questions/34975308/scene-kit-use-multiple-scnview-instances-side-by-side)?
Maybe using opengl in multiple views is not work fine.

**Comment by Meonardo** [comment]
@yshrkt Thanks, you are right. Do you have any idea how to solve the video play laggy issue?
