### ISSUE TITLE
Update for SDK 6.5.23?

### ISSUE THREAD

**Issue by dppeak** [yshrkt/VuforiaSampleSwift#31]
Are there plans to update this for support of version 6.5.23 of the SDK?

**Comment by vheun** [comment]
That would be my question as well ...

**Comment by DonatassVZ** [comment]
i am cant  search  new code for new version ( 6.5.23 now  dont working with this code)

**Comment by yshrkt** [comment]
Updated the vuforia sdk to v6.5.25.
