### ISSUE TITLE
SCN object shaky

### ISSUE THREAD

**Issue by smahurkar** [yshrkt/VuforiaSampleSwift#33]
The plane and the cube are fairly stable, however when I add an SCN object, it is very unstable i.e. it moves around with the camera. Could you look into this?

P.S. great project overall!

**Comment by yshrkt** [comment]
Hi, @smahurkar
Would this issue be  that a moving object become unstable?
Can you give me sample code or snippets, if you can possible.

**Comment by wlads** [comment]
Looks like duplicate #8 
I believe was solved in PR #41

**Comment by yshrkt** [comment]
@wlads thanks.
Once, I close this issue.
