### ISSUE TITLE
Issue with Viforia/UIGLViewProtocol.h file not found

### ISSUE THREAD

**Issue by tanalavijay** [yshrkt/VuforiaSampleSwift#34]

**Comment by yshrkt** [comment]
Hi, @tanalavijay
Which version of Vuforia SDK have you been using?

**Comment by muratyilmaz** [comment]
Hi, @tanalavijay 
if you are using 6-2-9 version of vuforia. 

Hear Search Paths | "$(SRCROOT)/VuforiaSampleSwift/vuforia-sdk-ios-6-2-9/build/include
Library Search Paths | $(PROJECT_DIR)/VuforiaSampleSwift/vuforia-sdk-ios-6-2-9/build/lib/arm
Objective-Bridging Header | VuforiaSampleSwift/VuforiaSampleSwift-Bridging-Header.h

But if you are using another version of Vuforia change version part of folder name.

**Comment by tanalavijay** [comment]
Thank you issue is solved .
I want to start unity ""start-unity-player-on-button-click" in iOS
