### ISSUE TITLE
Vuforia 7

### ISSUE THREAD

**Issue by fabrizotus** [yshrkt/VuforiaSampleSwift#35]
this example could be used with vuforia 7?

**Comment by yshrkt** [comment]
Hi, @fabrizotus 

This sample has updated to using Vuforia SDK v7.0.43.

**Comment by eisenbruch** [comment]
Does this work with Vuforia SDK v7.0.50, or only with .43?

**Comment by yshrkt** [comment]
@eisenbruch maybe this work with Vuforia SDK v7.0.50
