### ISSUE TITLE
Dragging an object

### ISSUE THREAD

**Issue by mackonen** [yshrkt/VuforiaSampleSwift#37]
Hi,

Thanks for the excellent sample. I've been trying to figure out how to move the object around. I noticed there's a touchesMoved placeholder in VuforiaEAGLView but no implementation. How would you go about implementing it?

**Comment by mackonen** [comment]
Do I have any way of accessing the touch positions in the ViewController.swift functions?

func vuforiaEAGLView(_ view: VuforiaEAGLView!, didTouchDownNode node: SCNNode!)
func vuforiaEAGLView(_ view: VuforiaEAGLView!, didTouchUp node: SCNNode!) 

I also noticed there's a touchesMoved function in the VuforiaEAGLView.mm but don't know how to use it...

**Comment by yshrkt** [comment]
Hi, @mackonen

If you want to move a object using touch, you can do by implementing touchesMoved function in the VuforiaEAGLView.mm like as bellow. 

```objc
- (void)touchesMoved:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    if(_currentTouchNode) {
        CGPoint pos = [touches.anyObject locationInView:self];
        pos.x *= [[UIScreen mainScreen] nativeScale];
        pos.y *= [[UIScreen mainScreen] nativeScale];
        pos.x = pos.x - _manager.viewport.origin.x;
        pos.y = _manager.viewport.size.height + _manager.viewport.origin.y - pos.y;
        SCNVector3 projectOrigin = [_renderer projectPoint: SCNVector3Make(0, 0, _currentTouchNode.position.z)];
        SCNVector3 vec3 = [_renderer unprojectPoint: SCNVector3Make(pos.x, pos.y, projectOrigin.z)];
        
        _currentTouchNode.position =  SCNVector3Make(vec3.x, vec3.y, _currentTouchNode.position.z);
    }
}
```
