### ISSUE TITLE
consultation

### ISSUE THREAD

**Issue by hibaMa** [yshrkt/VuforiaSampleSwift#38]
can i build like this application using swift vuforia and arkit 
https://www.youtube.com/watch?v=DXLyBQTS5-w

**Comment by yshrkt** [comment]
Hi, @hibaMa 

This video is very interesting. 
Maybe you can build app like this video using Vuforia.
I think it seems to be difficult to bulid app using ARKit, 
because ARKit do not include image target detection now.

**Comment by hibaMa** [comment]
thanks,
i was thinking to use vuforia for detecting the image and arkit to control the scene 
is it possible ?

**Comment by yshrkt** [comment]
Maybe, no.
ARKit and Vuforia require camera device each other independently.
So you will be not able to use those at same time.

If you want to use ARKit, Maybe you can use Vision.framework for image detection.

**Comment by yshrkt** [comment]
@hibaMa 
Apple released ARKit 1.5. 
New ARKit seems to be able to detect images.
You will able to build your application using only ARKit.
