### ISSUE TITLE
Unable to bind video background texture!!

### ISSUE THREAD

**Issue by LennardSennep** [yshrkt/VuforiaSampleSwift#46]
Getting this error right now when I want to run the app in my own build and the repo version

> Unable to bind video background texture!!

the error keeps popping up non-stop

![screen shot 2018-04-18 at 16 02 43](https://user-images.githubusercontent.com/28601422/38940424-02cc0d84-4322-11e8-9f04-c90f2758129d.png)

it is not related to https://github.com/yshrkt/VuforiaSampleSwift/issues/40 since I already added those shader files to the application

**Comment by yshrkt** [comment]
Hi, @LennardSennep 

Which version Xcode did you use to build?
It seems that Xcode 9.3 is not supported by current Vuforia SDK.
I got black screen...

https://library.vuforia.com/articles/Release_Notes/Vuforia-SDK-Release-Notes

**Comment by LennardSennep** [comment]
Hi @yshrkt,

Ah that might be it. Thanks for the explanation!
