### ISSUE TITLE
'Vuforia/UIGLViewProtocol.h' file not found & failed to emit precompiled header

### ISSUE THREAD

**Issue by kedarFlippar** [yshrkt/VuforiaSampleSwift#47]
![screen shot 2018-04-25 at 9 59 43 am](https://user-images.githubusercontent.com/32063608/39226336-7144cf60-486f-11e8-8502-90d455fce48f.png)
While compiling in Xcode 9.3, iOS 10. I'm getting following issues
1) 'Vuforia/UIGLViewProtocol.h' file not found
2) failed to emit precompiled header 

'/Users/apple/Library/Developer/Xcode/DerivedData/VuforiaSampleSwift-glchsoijgttrjxarsdqvdbuvxoqu/Build/Intermediates.noindex/PrecompiledHeaders/VuforiaSampleSwift-Bridging-Header-swift_124G2J8474IFF-clang_8FOSAOF2QAR9.pch' for bridging header '/Users/apple/Downloads/FlippAR Travel docs/Vuforia sample project/VuforiaSampleSwift-master/VuforiaSampleSwift/VuforiaSampleSwift-Bridging-Header.h'

Any solutions?

**Comment by yshrkt** [comment]
It looks like same issue of #48

**Comment by kedarFlippar** [comment]
@yshrkt able to resolve the issue by adding missing vuforia library files and setting correct header and search path

**Comment by yshrkt** [comment]
@kedarFlippar did you resolve this issue?

**Comment by kedarFlippar** [comment]
@yshrkt Yeah issue is resolved. Able to also use CloudReco class in swift 4, Xcode 9.2

**Comment by umbrella-alexey-rodshtein** [comment]
@kedarFlippar Can you tell me how to fix it?

**Comment by kedarFlippar** [comment]
@umbrella-alexey-rodshtein try adding vuforia sdk files manually to project. Seems like some files were displayed on Xcode but they were marked as red (file missing). Try adding those files manually
