### ISSUE TITLE
Vuforia/UIGLViewProtocol.h' file not found

### ISSUE THREAD

**Issue by strappvivek** [yshrkt/VuforiaSampleSwift#48]
Hi,

We have been trying to integrate Vuforia with our iOS app built using Swift. We have been getting this error: Vuforia/UIGLViewProtocol.h' file not found

We have also been facing issues with compiling - it shows up this error:
failed to emit precompiled header

Can you please advice why this could be happening?

thank you,

**Comment by yshrkt** [comment]
Hi @strappvivek 
Which version of Vuforia is you using?
You may need to set correct `Header Search Paths` and `Libarary Search Paths` in `Build Settings`

**Comment by strappvivek** [comment]
We have resolved that issue. We were missing a few files. thanks

**Comment by mattcoll** [comment]
@yshrkt Hi Yoshi, I am getting this same error.
'Vuforia/UIGLViewProtocol.h' file not found
I am using: vuforia-sdk-ios-7-2-23
I have made sure the paths are correct in Build Settings.
Do you have any ideas why I am getting this error still?
The file is definitely there.
![screen shot 2018-09-26 at 11 27 55 am](https://user-images.githubusercontent.com/19816080/46052889-77388400-c17f-11e8-9c57-d4de8d61820d.jpg)

Thanks

**Comment by samsuk1973** [comment]
> Hi @strappvivek
> Which version of Vuforia are you using?
> You may need to set correct `Header Search Paths` and `Libarary Search Paths` in `Build Settings`

**Comment by ujwalshrestha** [comment]
I am facing same issue. How did you solve this issue ?
