### ISSUE TITLE
Broken with Vuforia SDK v7.2.20

### ISSUE THREAD

**Issue by MatejBalantic** [yshrkt/VuforiaSampleSwift#55]
First of all thanks for great work making this happen with Swift & SceneKit.

Unfortunately, this project doesn't work with the latest version of Vuforia (and it's not possible to download legacy versions). 

I am pretty sure the reason is this:
<img width="1061" alt="screen shot 2018-07-18 at 03 24 33" src="https://user-images.githubusercontent.com/994179/42854024-21fc7aa4-8a3a-11e8-9beb-d44ff27ca67a.png">

I'd be happy to submit a PR, but have to admit I am a bit lost in the whole setup. Can you point me to the right direction to figure out how to migrate the coordinate systems to the new setup?

**Comment by yshrkt** [comment]
#61 merged
