### ISSUE TITLE
vuforia-sdk-ios-7-2-23

### ISSUE THREAD

**Issue by SlavaIsaev2020** [yshrkt/VuforiaSampleSwift#57]
Not work, help please

**Comment by SlavaIsaev2020** [comment]
can you send me 
https://github.com/yshrkt/VuforiaSampleSwift/issues Vuforia SDK v7.0.50?

**Comment by mattcoll** [comment]
@SlavaIsaev2020 What error are you getting?

@yshrkt I am getting this error in VuforiaEAGLView.mm = `Vuforia::COORDINATE_SYSTEM_CAMERA` 
Cannot initialize a parameter of type 'const Vuforia::CameraCalibration *' with an rvalue of type 'Vuforia::COORDINATE_SYSTEM_TYPE'

Are you able to please help with this?

Thanks

**Comment by yshrkt** [comment]
#61 merged
