### ISSUE TITLE
Unable to create context

### ISSUE THREAD

**Issue by byroncoetsee** [yshrkt/VuforiaSampleSwift#6]
Hi,

Thank you for this Sample. It has helped a lot!

I am having an issue though. The app builds and runs fine until I try scan an image. 

Log:

```
default scene
2016-09-14 12:24:53.142 Vuforia Swift[1549:1012606] INFO/AR(1549) 2016-09-15 12:24:53: Vuforia SDK version 6.0.112
2016-09-14 12:24:53.245 Vuforia Swift[1549:1012606] Rendering mode set to: OpenGL ES 2.0
2016-09-14 12:24:53.291 Vuforia Swift[1549:1012606] Rendering mode set to: OpenGL ES 2.0
2016-09-14 12:24:53.293 Vuforia Swift[1549:1012444] DEBUG/AR(1549) UIView has CAEAGLLayer layer class
2016-09-14 12:24:53.293 Vuforia Swift[1549:1012444] DEBUG/AR(1549) UIView responds to selector renderFrameVuforia
2016-09-14 12:24:53.331 Vuforia Swift[1549:1012635] loadObjectTrackerDataSet (Stones.xml)
2016-09-14 12:24:53.333 Vuforia Swift[1549:1012635] INFO/AR(1549) 2016-09-15 12:24:53: ObjectTracker: Successfully created dataset
2016-09-14 12:24:53.334 Vuforia Swift[1549:1012635] INFO: successfully loaded data set
2016-09-14 12:24:53.388 Vuforia Swift[1549:1012635] Successfully activated data set.
did finish preparing

2016-09-14 12:24:53.415 Vuforia Swift[1549:1012635] VideoBackgroundConfig: size: 750,1334
2016-09-14 12:24:53.416 Vuforia Swift[1549:1012635] VideoMode:w=1280 h=720
2016-09-14 12:24:53.416 Vuforia Swift[1549:1012635] width=750.000 height=1334.000
2016-09-14 12:24:53.417 Vuforia Swift[1549:1012635] ViewPort: X,Y: 0.0,0.0 Size X,Y:750.0,1334.0
2016-09-14 12:24:53.693 Vuforia Swift[1549:1012492] Deleting old image data @ 0x0
2016-09-14 12:24:53.693 Vuforia Swift[1549:1012492] Created new image data buffer @ 0x106838000 w/ 1382400 bytes
stones scene
2016-09-14 12:24:56.750 Vuforia Swift[1549:1012444] SceneKit: error, Unable to create context
2016-09-14 12:24:56.751 Vuforia Swift[1549:1012444] SceneKit: error, Unable to create context
```

I'm also wondering if it's possible to use my own camera manager using this: https://github.com/imaginary-cloud/CameraManager

Again, thank you :)

PS. If you would like any of the files I've used for target, let me know... I didn't use yours (as they did not come with the zip I downloaded)

**Comment by yshrkt** [comment]
@byroncoetsee 
Thank you for reporting.
I got same error log, but this sample works fine.
It seems to be happen in SceneKit...

> I'm also wondering if it's possible to use my own camera manager using this:

It's maybe difficult to implement, because Vuforia SDK has own camera manager.

> PS. If you would like any of the files I've used for target, let me know... I didn't use yours (as they did not come with the zip I downloaded)

Sorry, I can't bundle vuforia's sample target.

**Comment by byroncoetsee** [comment]
Hey thank you for the response :)

Could you maybe give me a rough idea of where this SceneKit error could be coming in? Where does the actual image get drawn? 

You say you are also getting the `SceneKit: error, Unable to create context` error or not?

**Comment by yshrkt** [comment]
> Could you maybe give me a rough idea of where this SceneKit error could be coming in? Where does the actual image get drawn?

It seems to be happen in `[_renderer renderAtTime:]` only first time, after setting scene to renderer.
This sample is drawn frame at VuforiaEAGLView's `renderFrameVuforia` method.

> You say you are also getting the SceneKit: error, Unable to create context error or not?

Yes, but works fine.

**Comment by byroncoetsee** [comment]
It seems if I comment out `_renderer.showsStatistics = YES;` within `setupRenderer`, the errors go away... I'm still not getting any object overlaid on screen though.

I am using the stones from "http://developer.vuforia.com/sites/default/files/sample-apps/targets/stones.pdf" by the way

**Comment by byroncoetsee** [comment]
Finally got the box to show! Had to use a different XML file (even though the one I was using came from Vuforia sample)... Error still shows but I don't care - I'm just glad something is showing.

Thank you again from South Africa :D

**Comment by yshrkt** [comment]
👍

**Comment by jhudziak** [comment]
When i load and activate DataSet from background thread this error disappears.

**Comment by byroncoetsee** [comment]
@yshrkt do you think we will ever see this written in Swift? Or a more modern class used like GLKView instead of EAGLView... Just wondering :)

**Comment by byroncoetsee** [comment]
The reason I ask is, I'm not very good with Objective-C and I'm bad at C++.

I'm trying to restart a scene (there is a video playing in that scene on a spritekit) when it goes off the screen and comes back on. Currently, the music keeps playing when the camera is turned away from the target. I need it to stop playing and restart when the camera faces the target again.

Current scene creation with video:

```
private func createVideoScene(with view: VuforiaEAGLView) -> SCNScene {
		let scene = SCNScene()
		
		// create the asset & player and grab the dimensions
		let path = NSBundle.mainBundle().pathForResource("VuforiaSizzleReel_1", ofType: "mp4")!
		let asset = AVAsset(URL: NSURL(fileURLWithPath: path))
		let size = asset.tracksWithMediaType(AVMediaTypeVideo)[0].naturalSize
		
		let player = AVPlayer(playerItem: AVPlayerItem(asset: asset))
		print(player.rate)
		
		// setup the video SKVideoNode
		let videoNode = SKVideoNode(AVPlayer: player)
		videoNode.size = size
		videoNode.position = CGPoint(x: size.width * 0.5, y: size.height * 0.5)
		
		// setup the SKScene that will house the video node
		let videoScene = SKScene(size: size)
		videoScene.addChild(videoNode)
		
		// create a wrapper ** note that the geometry doesn't matter, it happens with spheres and planes
		let videoWrapperNode = SCNNode(geometry: SCNBox(width: 2, height: 2, length: 2, chamferRadius: 0))
		videoWrapperNode.position = SCNVector3(x: 0, y: 0, z: 3)
		
		// set the material's diffuse contents to be the video scene we created above
		videoWrapperNode.geometry?.firstMaterial?.diffuse.contents = videoScene
		videoWrapperNode.geometry?.firstMaterial?.doubleSided = true
		
		// reorient the video properly
		videoWrapperNode.scale.y = -1
		
		// add it to our scene
		scene.rootNode.addChildNode(videoWrapperNode)
		return scene
	}
```

**Comment by yshrkt** [comment]
@byroncoetsee 
> @yshrkt do you think we will ever see this written in Swift? Or a more modern class used like GLKView instead of EAGLView... Just wondering :)

We needs call C++ function in EAGLView. so, can't write it in swift.😣
I wish to write more swifty, too.

> I'm trying to restart a scene (there is a video playing in that scene on a spritekit) when it goes off the screen and comes back on. Currently, the music keeps playing when the camera is turned away from the target. I need it to stop playing and restart when the camera faces the target again.

In my situation, handled the event which turned away the target in VuforiaManagerDelegate's `didUpdateWithState` method.

For example:
```swift
func vuforiaManager(manager: VuforiaManager!, didUpdateWithState state: VuforiaState!) {
        if state.numberOfTrackableResults == 0 {
            // Not track any target.
            // In my case, animate for hideing.
            // In your case, stop video.
            player.stop()
            return
        }
        if state.trackableResultAtIndex(0).status == VuforiaTrackableResultStatus.Tracked {
            // Tracked some target.
            // In my case, animate for showing.
            // In your case, start video if needed.
            if !player.playing {
                player.play()
            }
        }
}
```

**Comment by byroncoetsee** [comment]
Yeah I actually solved it the exact same way eventually 💃 Thanks

Have you ever tried overlaying a video onto the scene? If so, did it play at normal speed? ...I've added a video with the following code:

```
private func createVideoScene(with view: VuforiaEAGLView) -> SCNScene {
		let scene = SCNScene()
		
		// create the asset & player and grab the dimensions
//		let path = NSBundle.mainBundle().pathForResource("VuforiaSizzleReel_1", ofType: "mp4")!
		let path = NSBundle.mainBundle().pathForResource("GS_Training", ofType: "mov")!
		let asset = AVAsset(URL: NSURL(fileURLWithPath: path))
		let size = asset.tracksWithMediaType(AVMediaTypeVideo)[0].naturalSize
		
		player = AVPlayer(playerItem: AVPlayerItem(asset: asset))
//		let player = AVPlayer(URL: NSURL(string: "https://inm-baobab-prod-eu-west-1.s3.amazonaws.com/public/inm/media/video/2016/09/02/61537094SansSouciGirlsSchool.mp4")!)
//		player!.addObserver(self, forKeyPath: "rate", options: [NSKeyValueObservingOptions.Initial, NSKeyValueObservingOptions.New], context: nil)
		
		
//		let playerLayer = AVPlayerLayer(player: player)
//		playerLayer.videoGravity = AVLayerVideoGravityResizeAspectFill
		//playerLayer.frame = CGRect(origin: CGPoint(x: size.width * 0.5, y: size.height * 0.5), size: size)
		
		// setup the video SKVideoNode
//		let videoNode = SKVideoNode(AVPlayer: player)
		let videoNode = SKVideoNode(videoURL: NSURL(fileURLWithPath: path))
		videoNode.size = size
		videoNode.position = CGPoint(x: size.width * 0.5, y: size.height * 0.5)
		currentVideoNode = videoNode
		
		// setup the SKScene that will house the video node
		let videoScene = SKScene(size: size)
		videoScene.addChild(videoNode)
		
		// create a wrapper ** note that the geometry doesn't matter, it happens with spheres and planes
		let videoWrapperNode = SCNNode(geometry: SCNPlane(width: 10, height: 8))
		videoWrapperNode.position = SCNVector3(x: 0, y: 0, z: 2)
		
		// set the material's diffuse contents to be the video scene we created above
		videoWrapperNode.geometry?.firstMaterial?.diffuse.contents =  videoScene
		videoWrapperNode.geometry?.firstMaterial?.doubleSided = true
		
		// reorient the video properly
		videoWrapperNode.scale.y = -1
		
		// add it to our scene
		videoWrapperNode.name = "videoWrapper"
		scene.rootNode.addChildNode(videoWrapperNode)
		
//		videoWrapperNode.runAction( SCNAction.repeatActionForever( SCNAction.rotateByAngle(CGFloat(M_PI * 2.0), aroundAxis: SCNVector3(x: 0, y: 1, z: 0), duration: 15.0 )))
		return scene
	}
```
(Sorry ignore all the comments and repeated code - still busy hacking it together 😜  )

The video plays at almost 5 times the speed it should but the sound plays correctly... Do you have any experience with this?

**Comment by yshrkt** [comment]
> Have you ever tried overlaying a video onto the scene? If so, did it play at normal speed?

I have never use SKVideoNode.
Can your video play correctly using AVPlayerLayer?

**Comment by byroncoetsee** [comment]
I've tried AVPlayerLayer. If I add it to my scene (via SCNNode), it doesnt play the video - only the audio.
I'm currently trying to render the scene on main thread... Maybe that makes a difference somehow.

**Comment by yshrkt** [comment]
I tried your code. SKVideoNode seems to not work well.
Also AVPlayerLayer can use only macOS. (Sorry...)
You will need to create texture using AVPlayerItemVideoOutput.

**Comment by andyweiqiu** [comment]
@byroncoetsee I have the same problem.But there is no solution.Did you solve it？
