### ISSUE TITLE
Vuforia V7.5.20 and Swift 

### ISSUE THREAD

**Issue by fabiopratta** [yshrkt/VuforiaSampleSwift#60]
@yshrkt 

I made some modifications to the code made available to run with the most current version of the vuforia, it compiles everything normal.

But it seems that it does not render the SCNScene or something, I'll leave the link if someone else wants to help with this migration.

https://github.com/fabiopratta/Vuforia-7-5-20-and-Swift

Who can run with everything running put git to update the code.

Thank you.

**Comment by OknestaDeveloper** [comment]
yes( Help(

**Comment by nleclerc** [comment]
I've got it mostly working there : https://github.com/nleclerc/VuforiaSampleSwift/tree/vuforia75
There's still a strange rendering fov issue but it's almost there :-D

**Comment by nleclerc** [comment]
Alright, fixed the viewport issue and it's working 100% now.

**Comment by ikovalisko** [comment]
@nleclerc just tried you branch and worked for me 👍

**Comment by yshrkt** [comment]
#61 merged
