### ISSUE TITLE
UIKit element possible to overlay?

### ISSUE THREAD

**Issue by markleeyw** [yshrkt/VuforiaSampleSwift#7]
SCNNode items can be shown when target detected. But isit possible to overlay UIKit element like button or image ?

**Comment by yshrkt** [comment]
Do you mean that the UIKit elements are overlayed on camera preview?
If so, yes, It's possible like below:

```
self.view = vuforiaManager.eaglView
let imageView = UIImageView()
self.view.addSubview(imageView)
```

**Comment by markleeyw** [comment]
okay thank you. All is working. But Can I add a SCNView as a subview
    var sceneView: SCNView!
       sceneView = SCNView(frame: self.view.frame)
        sceneView.scene = SCNScene()
        self.view.addSubview(sceneView)

Does not seem to work when I try to show an animating box for example.

**Comment by yshrkt** [comment]
@markleeyw 

I tried it in Issue #9
