### ISSUE TITLE
Model shaking

### ISSUE THREAD

**Issue by jhudziak** [yshrkt/VuforiaSampleSwift#8]
Hello,

I have a problem with shaking 3D models. I do not know why, but in some cases even I put the phone on something stable models are constantly shaking. Options ExtendedTracking and continuousAutofocus are enabled. The target has 5 stars and have been tested as printed version and on different monitors.

Do you maybe have some ideas why this happens?

Regards, JH

**Comment by yshrkt** [comment]
@jhudziak 
Do you get same problem using other image target or simple model (like a box)?
Umm..., some hints might exist in vuforia forum.
https://developer.vuforia.com/search/apache_solrsearch/Shake?fq%5B%5D=bundle%253Aforum

**Comment by jhudziak** [comment]
In downloaded sample and the box is not shake, but if you fast move phone or tablet SCNNode - box act as jelly, it swims. Every device move makes every nodes try to adapt its position. If you try Vuforia sample Image Targets you see that the cup is stil i same place. This situations is easy to spot if you look at the edges of target stones and node with plane geometry.

I try to find a difference between this sample and Vuforia and they are almost same.
Do you have any idea why is a big difference?

JH

**Comment by yshrkt** [comment]
I think my sample has overheads caused by using SceneKit.
On the other hand, Vuforia's sample is rendered using OpenGLES directly.
In my usecase, my sample has enough performance. So I don't think as big difference. 
But I think my sample still has a lot of possibilities to tuning the performance.

**Comment by jhudziak** [comment]
I don't have much experience in Scenekit :(. 
Maybe you could do something with this, or indicate how to try correct it?

**Comment by yshrkt** [comment]
Sorry, I am not working with this issue now.
I think this issue is very hard...

**Comment by MashaelSaeedi** [comment]
Hi 
the 3D cube doesn't show up.. the code works fine, i putted a print statement inside createStoneScene  function to make sure the it pass through it. it passes but nothing drawn in the camera when i run it!! 

any Suggestions? 
thanks!!
